### ISSUE TITLE
Not all merged PRs are included in the release notes

### ISSUE THREAD

**Issue by TWiStErRob** [rudderlabs/rudder-typer#100]
Compare
 * https://github.com/rudderlabs/rudder-typer/releases/tag/v1.3.1
 * https://github.com/rudderlabs/rudder-typer/compare/v1.3.0...v1.3.1

**Comment by akashrpo** [comment]
Hi @TWiStErRob,

Thank you for raising this issue!

I believe the problem lies in the PR title format. We didn't use the appropriate tags, such as `feat:` or `fix: followed by words in lowercase`. As a result, the changes weren't properly reflected in the release tag.

For reference: [Commit Link](https://github.com/rudderlabs/rudder-typer/pull/97/commits).
To resolve this moving forward, we should ensure that the next PR includes the correct title format to automatically include those changes.

In the meantime, I have manually added those commits to the previous release.

Thank you for bringing this up!
